apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image
  namespace: default
spec:
  tag: "ghcr.io/ds886/k8s-test:test"
  serviceAccountName: kpack
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/Ds886/test-k8s.git
      revision: f0921ba4d689d3c7524208a674555a3d99ada10d
