#!/bin/sh
set -eux
# source: https://github.com/SUSE/suse-at-home/blob/main/install/InstallK3s.md

set +u
CURR_ID=$(id -u)
[ "${CURR_ID}" != "0" ] && echo err: must run as root && exit 1

#BINS
ZYPPER="$(which zypper)"
[ -z "${ZYPPER}" ] && echo "err: not on suse" && exit 1

PATH_TEMP="$(mktemp -d)"
PATH_K3S_SCRIPT="$PATH_TEMP/k3s.sh"

PORT_LIST=
GLASS_MODE="false"
[ -z "${PORT_LIST}" ] && GLASS_MODE="true"

K3S_SCRIPT_SHA="489b15ca32b3c361908994be45489633"
K8S_VERSION="v1.27.11+k3s1"
# shellcheck disable=2034
K8S_KUBECONF_MODE="0644"

export K3S_KUBECONFIG_MODE="${K3S_KUBECONFIG_MODE}"
export INSTALL_K3S_VERSIONON="${K8S_VERSION}"
set -u


"${ZYPPER}" up
"${ZYPPER}" in which

if [ "${GLASS_MODE}" = "true" ]
then
	sudo systemctl disable --now firewalld
else
	for PORT_ITEM in ${PORT_LIST}
	do
		firewall-cmd --zone=public --add-port="${PORT_ITEM}" --permanent
	done
	firewall-cmd --reload
fi

# add install-path to sudo
# We already check we are root on top
# We first create temp folder for safety(race condition when writing to the same file)
# shellcheck disable=2094
sed 's,^Defaults secure_path="/usr/sbin:/usr/bin:/sbin:/bin$",Defaults secure_path="/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin",g' "/etc/sudoers" > "${PATH_TEMP}/sudoers"
cp /etc/sudoers /etc/sudoers.old
mv "${PATH_TEMP}/sudoers" "/etc/sudoers"

curl -sfLo "$PATH_K3S_SCRIPT" https://get.k3s.io
chmod +x "${PATH_K3S_SCRIPT}"

CURR_DL_SUM=$(md5sum "${PATH_K3S_SCRIPT}"| cut -f1 -d\ )
[ "${CURR_DL_SUM}" != "${K3S_SCRIPT_SHA}" ] && echo err: download corrupted  && exit 1
"${PATH_K3S_SCRIPT}"

echo "    --write-kubeconfig-mode=644 \\" | sudo tee -a /etc/systemd/system/k3s.service
echo "" | sudo tee -a /etc/systemd/system/k3s.service
systemctl daemon-reload
systemctl restart k3s

cat <<EOF > /etc/profile.d/k3s.sh
	export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
EOF

# sudo in  suse doesnt load profile
mkdir -p /root/.kube
rm -f /root/.kube/config
ln -sf "/etc/rancher/k3s/k3s.yaml" "/root/.kube/config"


echo "cleaning"
rm -rf "$PATH_TEMP"
