{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpack.serviceAccountName" . }}
  labels:
    {{- include "kpack.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
{{- range .Values.serviceAccount.dockerSecret }}
- name: {{ . }}
{{- end }}
imagePullSecrets:
{{- range .Values.serviceAccount.dockerSecret }}
- name: {{ .}}
{{- end }}
{{- end }}
