apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: tutorial-image
  namespace: default
spec:
  tag: "ghcr.io/ds886/simplejava:latest"
  serviceAccountName: kpack
  builder:
    name: my-builder
    kind: Builder
  source:
    git:
      url: https://github.com/Ds886/simplejava.git
      revision: main
