#!/bin/sh
set -eux
CURR_ID=$(id -u)
[ "${CURR_ID}" != "0" ] && echo err: must run as root && exit 1

set +u

# BIN
set +e
CURL="$(command -v curl)"
set -e
[ -z "${CURL}" ] && echo "curl not found" && exit 1

#PATH
PATH_TEMP="$(mktemp -d)"
FLUX_URL="https://fluxcd.io/install.sh"
FLUX_HASH="bd7765225b731a1df952456eced0abb5dbbf5e11bc70cf6ab5fddd1476088b7e"

set -u


# https://github.com/buildpacks-community/kpack-cli/releases/download/v0.13.0/kp-linux-amd64-0.13.0
curl -Lo "${PATH_TEMP}/install.sh" "${FLUX_URL}"
chmod +x "${PATH_TEMP}/install.sh"
set +e
CURR_DL_SUM=$(sha256sum "${PATH_TEMP}/install.sh"| cut -f1 -d\ )
[ "${CURR_DL_SUM}" != "${FLUX_HASH}" ] && rm -rf "${PATH_TEMP}" && echo "err: download corrupted"  && exit 1
"$PATH_TEMP/install.sh"
set +e
flux -v
KP_EXIT_CODE="$?"
set -e
[ "${KP_EXIT_CODE}" != 0 ] && echo "err: kp have a runtime issue" && exit 1
rm -rf "${PATH_TEMP}"
