#!/bin/sh
set -eux

set +e
FLUX="$(command -v flux)"
[ -z "${FLUX}" ] &&  echo "please install flux" && exit 1
set -e

set +e
FLUX="$(command -v flux)"
set -e
[ -z "${FLUX}" ] && echo "tried to install flux but failed" && exit 1

GH_TOKEN="<add token>"
GITHUB_TOKEN="${GH_TOKEN}"
export GITHUB_TOKEN
GH_USER="<add user>"
GH_REPO_FLUX="<insert repo>"

FLUX_FEATURES="source-controller,kustomize-controller,helm-controller,notification-controller"
FLUX_FEATURES_EXTRAS="image-reflector-controller,image-automation-controller"
FLUX_NETWORK_POLICY="false"


# Bootstrap
# https://fluxcd.io/flux/installation/bootstrap/github/
# shellcheck disable=2097
"${FLUX}" bootstrap github \
  --token-auth \
  --owner="${GH_USER}" \
  --repository="${GH_REPO_FLUX}" \
  --branch=main \
  --path=clusters/my-cluster \
  --personal \
	--components "${FLUX_FEATURES}" \
	--components-extra "${FLUX_FEATURES_EXTRAS}" \
	--network-policy "${FLUX_NETWORK_POLICY}" \
  --private

./installflux-conf
