{{- range .Values.repos }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: "{{ .name }}-gitrepo-{{ template fluxconfig.fullname }}"
  namespace: "{{ .Values.general.namespace }}"
spec:
  interval: 1m0s
  ref:
    branch: "{{ .ref }}"
  url:  "{{ .repo }}"
{{- end }}
