---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-localrepo
  namespace: "{{ .Values.general.namespace }}"
spec:
  interval: 1m0s
  url: "{{ .Values.helm.repo  }}"
